---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx
  namespace: staging
spec:
  selector:
    matchLabels:
      run: react-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: react-nginx
    spec:
      containers:
      - name: react-nginx
        image: $ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-ecr:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
            
            